### PR TITLE
Fix types mismatches

### PR DESCRIPTION
**Pull request by picryott**
* Also use standard library for booleans

There were mismatches between declarations and definitions of some boolean functions and variables. 
There was also a misuse of "~" on a boolean.

And I suggest using the standard library for booleans (stdbool.h).
That raised bug where guards harassed innocent prisonners because "authorized_id" was declared as boolean instead of u16. Fixed.

Built on Windows 10 
Microsoft Visual Studio Community 2017 
Version 15.1 (26403.7) Release
VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.7.02046

Happily tested on Windows 10 and PPSSPP.

### CODE REVIEW

**Comment by aperture-software** [comment]
I think that's a good proposal. The reason stdint/stdbool were not used was that, at the time, Visual Studio did not have them, but since we no longer care about these old versions, now's a good time to improve on this.

**Comment by picryott** [comment]
Hello,

I have a commit ready for stdint.h.

I will pull a request soon.

In fact, I am trying to get rid of the whole data-types.h.


I also have plans for a linux version, which is my personal goal.

I already have a working linux version but with no videoplayer and no 
modplayer.

I use openal for sound but it lacks callbaks, so It's a bit complicate 
for the modplayer.

**Comment by aperture-software** [comment]
> I have a commit ready for stdint.h. I will pull a request soon.

Okay. I don't mind modifying your request either, though I don't know how soon I'll be able to do that.

> I am trying to get rid of the whole data-types.h.

That makes sense. Once we have stdint/stdbool, that file would become pretty much useless, especially as `min()` and `max()` can be found in `stdlib.h` on Visual Studio (not sure about gcc, but there's probably a way not to have to define them in `data-types.h` too.

> I also have plans for a linux version, which is my personal goal.

That would be __AWESOME__!!!

I was actually pleasantly surprised that, even though it's very old technology, GLUT/OpenGL still seems to work just fine on Windows 10, and I am hoping GLUT usage on Linux is also working in modern distros, so as not to make porting too much of a hassle.

> no videoplayer and no modplayer.

Yeah, I had to write custom code for those. Hopefully someone has already done something like that for Linux, and you can reuse their code. If you need help, let me know!

**Comment by aperture-software** [comment]
Okay, I have now applied your fixed size ints patch and also removed `data-types.h`.

**Pull request closed without merging**
