### PR TITLE
Linux build.

### PR DESCRIPTION
**Pull request by picryott**
* known issues:
  - no SFX
  - no Modplayer
  - no Videoplayer
  - keyboard configuration not fully functional

* code modifications
  - add types to the parameters of guard_close_by to guard_collision. gcc warned about those missing types.
  - rename macro "menu" to "game_menu". There seemed to be conflicting replacements. 
  - add linux implementations for msleep, mtime
  - replaced some #if !defined(PSP) with #if defined(WIN32) for windows only features
  - add some includes

* build procedure:
  make -f linux.mak

Built and tested on debian  4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux
with gcc (Debian 6.3.0-18) 6.3.0 20170516

I will try to add support for sound and video.
Tell me if there are things you do not want to include in the project (for licensing reasons, or whatever you want ).
I would like to use portable libraries so that we could remove many (all) the #if defined(OS).

### CODE REVIEW

**Comment by aperture-software** [comment]
Thank you very much for this!

It might be another few days before I can take a closer look at this, but from what I can see, I definitely want to have Linux support for the next release. 👍

**Comment by aperture-software** [comment]
With regards to your questions:

> I will try to add support for sound and video.

Sounds good. I'll see if I can have a look at it too, as I'd be surprised if someone hasn't coded a GPLv3 compatible modplayer and other stuff for Linux. Or, more likely, I think I should be able to add Linux compatibility to the existing soundplayer code.

> Tell me if there are things you do not want to include in the project (for licensing reasons, or whatever you want ).

Everything that's part of the project is GPLv3, apart from the original binary files, which I can only consider abandonware at this stage, and therefore open for fair use, so there really isn't anything that you can't include.

> I would like to use portable libraries so that we could remove many (all) the #if defined(OS).

I'd rather avoid that.

For one thing, even if PSP support is not something I want to focus strongly on, I doubt you'll find any portable libraries that is compatible with Linux/Windows/PSP. The only one I found was GLUT/OpenGL (which is precisely why it is being used by the project), but that only covers graphics.

Plus I don't think that video/sound/modplayer code should be so hard to modify for Linux compatibility, to warrant the use of a library, if that's what you are trying to avoid. I'd rather see time invested learning how to interact with the OS high-level sound and video APIs (which is something any modern OS will provide, such as through Windows' DirectX' XAudio2 or IMedia), than trying to shove yet another library in the project.

Then again, I don't want to force you into doing something you're uncomfortable with. But there's a good chance that, if you try to use a nonstandard Linux library, I'll be spending time trying to remove it from the project (which, as I said before, I don't really mind, as I've always wanted to explore the Linux audio & video subsystem 😄).

**Comment by picryott** [comment]
Hello,

I found a lib that should do the trick : mikmod

I knew its name but I never used it before as I have never used sound in 
my projects.

It plays MODS (and much more) and can be used to play SFXs.

It's in the debian repositories (libmikmod is LGPL).

Plus it's compatible with win32, PSP and Linux.

I will give it a try (already tried it for a standalone modplayer, very 
easy).

I hope to have a full soundsystem working this week(end).

**Comment by aperture-software** [comment]
I'm gonna be honest: personally I think mikmod will be an overkill. We already have the code for a mod player, that works for both win32 and psp, and all that's actually needed to make it work for Linux is figure out how to send sound data to the Linux subsystem.

I can understand that you prefer not to have to modify unfamiliar code, but I'm not too fond of adding another library while there's a good chance that making the existing mod player work with Linux is relatively straightforward, if one acquires some elementary knowledge of the Linux sound system (and yes, this may require writing custom C code, but I don't think it will be that much code).

So, even if you provide a patch using mikmod, I have to tell you that the first thing I'll still do is try to see if we can modify the mod player code to interact with the Linux sound system directly, so that we can avoid having to add the mikmod dependency.

On the other hand, since it's the same license, you can take a look at the mikmod code for Linux to figure out how they interact with the Linux sound API, and use that to alter the existing sound player / mod player code.


As to the video player, Right now, I think I will remove the videos altogether, so that shouldn't be needed. This was only ever used to play my custom "Aperture Software" intro, and I don't think it brings much, as I don't need to see that name plastered everywhere and it looks a bit too amateurish now. Plus it adds a couple MB to the download. So, what is likely to happen is that I'll remove the intro and the video player, which means that all that's needed to complete the Linux port is sound.

**Comment by aperture-software** [comment]
Okay, I have modified your patch a little bit, and will be pushing it to the repo, which will close this request.

I have split the PSP and Linux Makefiles into `Makefile.linux` and `Makefile.psp` with a parent `Makefile` that will automatically detect the platform and invoke the relevant one, so that you can just run: `make release` and it will just work.

Also, I made sure to use `#if defined(__linux__)` instead of `#if defined(linux)`, as the last one is not POSIX compliant.

I also did away with creating sub directories for objects and binaries, as I don't feel it is warranted, and I personally think trying to split everything all over the place in subdirectories is a waste of time.

Finally, you'll see that I moved to building GLUT from the included source, rather than use the system dependency, as we already have the source for Windows anyway, and I'd like to have some control over it for XBox 360 Controller support if needed.

**Comment by aperture-software** [comment]
Just to point out that I have now removed video support, and I also added shader support for Linux (with SABR being used by default). See fce655499b02dd68215bdc0d24b2eae038b3bf9b for details.

**Comment by aperture-software** [comment]
Since I had a bit of time and wanted to see what was the deal with the state of Linux Audio in 2017, I added initial audio support using ALSA/libasound in  17ae204197c0785c0814c590ca222ecd8be6bc29. I found that ALSA was not that hard to integrate into `soundplayer.cpp`, but the problem is that it lacks several major features, the most critical one being the ability for its PCM interface to use multiple channels/voices to play multiple SFXs to the same output at the same time. 

I really find it hard to believe that after all the fuss the ALSA people made about how they would create a sound subsystem that was so much better than the old OSS, they still didn't manage to provide Linux developers with something that was even remotely half useful! Any other system I know (starting with the Amiga), provides the ability to play multiple voices simultaneously, or set an individual volume level for an SFX, but ALSA can't? Talk about a massive letdown...

Still, I'm hoping that we might be able to use the ALSA mixer API to downmix a virtual 5.1 output to mono or stereo, and therefore achieve what we need. But sheesh, I really thought it wasn't possible for Linux to miss the mark even worse than Microsoft in terms of API features...

**Comment by picryott** [comment]
OK, I won't send a pull request for this work.

I will keep it in my fork.

**Comment by picryott** [comment]
I think, you could consider using a build generator like CMake instead of multiplying the makefiles.

I take note for the __linux__ . I do not use that frequently but when I do, I always guess what's the correct one.

I always keep my products separated from the sources. I find it easier to navigate. I don't want to configure my IDE to ignore the products when I can just avoid to open a folder.

I don't like the idea to have other libraries sources in my projects. The binaries should be sufficient.

Modifying other libraries in your own project is not a good idea even with version control (professional experience).

But, hey, this is your project ! And you did an awesome job making it work.

I would never have guessed someone would have recoded this particular game, until I found it by chance :)

**Comment by picryott** [comment]
Yes, that's a reason why I did not want to go too low level and gave OpenAL a try.

But even with that, I was a little disappointed.

I have no experience with sound programming. So I'm sorry, I can't help much.

**Comment by aperture-software** [comment]
> I won't send a pull request for this work. I will keep it in my fork.

Okay. I'm sorry to have shut down your proposal on this one, but part of the reason I made Colditz Escape is so I could learn about various subsystems, and I see this as too good an opportunity to learn about ALSA to pass it up by using a high level library.

> I think, you could consider using a build generator like CMake instead of multiplying the makefiles.

If I felt the need for a Makefile generators, I'd be using autotools, which I am quite familiar with, instead of CMake. I used CMake it the past, and I can't say I'm impressed with it. But having 2 very simple Makefiles doesn't count as requiring the need to use autotools, or switch to a different approach.

> I don't like the idea to have other libraries sources in my projects. The binaries should be sufficient.

Well, the problem is: GLUT had no proper support for an XBox 360 controller DPAD and also its icon handling for Windows was completely broken, which is why I had to alter it. I have some vague plans to maybe switch to freeGLUT eventually, if it does a better job than GLUT, but GLUT was not that heavy to add into the project, and it's much better to have a library that does exactly what you want, than have to contend with one that doesn't. Same goes for Expat, as you probably noticed that, on Linux, it complains about the `&#x00;` sequences from the `config.xml` file, because, IMO, there's no reason why an XML parser shouldn't be able to accept such sequences, and I did craft my own version of the library for Windows and PSP to accept just that. However, I don't think I want to go as far as asking a modified version of Expat into the project, so I'll probably have to apply a workaround.

> I have no experience with sound programming. So I'm sorry, I can't help much.

That's fine. I don't have much experience either, but I'm eager to learn, so I don't think I'll need your help on that, and that'll also help me abstract the audio backends, which is probably something I should have done from the get go.

**Comment by picryott** [comment]
> If I felt the need for a Makefile generators, I'd be using autotools, which I am quite familiar with, instead of CMake. I used CMake it the past, and I can't say I'm impressed with it. But having 2 very simple Makefiles doesn't count as requiring the need to use autotools, or switch to a different approach.

   3 makefiles! Don't forget windows :)

> Same goes for Expat, as you probably noticed that, on Linux, it complains about the `&#x00;` sequences from the `config.xml` file, because, IMO, there's no reason why an XML parser shouldn't be able to accept such sequences, and I did craft my own version of the library for Windows and PSP to accept just that. However, I don't think I want to go as far as asking a modified version of Expat into the project, so I'll probably have to apply a workaround.

Yes, that's one of the first thing I noticed. Just like you, I couldn't understand why &#x00 was not handled by XML. So for my very first versions on linux, I dropped all the XML stuff and switched to a good old keys/values file.

Maybe you could just rethink the way the keycodes are stored in the XML file.

**Comment by aperture-software** [comment]
> 3 makefiles! Don't forget windows

Hehe, if you wanna go that way, that would be 4 if we count the one for GLUT. Still not enough to warrant switching to autotools. By all standards, this is a small project.

Anyway, just gonna point out that the audio on Linux should be sorted out now (including playout of the intro mod file). Feel free to check it out.

**Pull request closed without merging**
